name: 'terraform_destroy'

on:
    workflow_dispatch:
      inputs:
        logLevel:
          description: 'Log level'     
          required: false
          default: 'warning'
        tags:
          description: 'Test scenario tags'  


permissions:
    contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    # environment: prod
    env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0 # specify your Terraform version

    - name: Terraform Init
      run: terraform init -backend-config=bucket="lab-terraform-back-end" -backend-config=key="key/terraform.tfstate" -backend-config=region="eu-west-2"

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      
